### ISSUE TITLE
unable to use ctpu again

### ISSUE THREAD

**Issue by yangw502** [tensorflow/tpu#147] opened 2018-07-11 06:42 UTC
@saeta My computer suddenly shut down yesterday, when my VM was running.  Now, I am unable to get into the VM by $ ctpu up . I get the following errors:
2018/07/11 13:03:47 googleapi: Error 403: Read access to project 'test' was denied, forbidden

**Comment by chrislarkin** [comment] 2018-07-11 12:46
@yangw502, when you run `ctpu cfg` does the zone displayed match the zone your project was created in? If not, passing the `zone` flag _should_ work. Alternately, if you don't want to pass the flag every time, it can be set [globally](https://github.com/tensorflow/tpu/tree/master/tools/ctpu#global-flags):

`gcloud config set compute/zone us-central1-b` (or whichever zone is appropriate)

If you've already tried these steps & are still having trouble, please let us know- thanks!

**Comment by yangw502** [comment] 2018-07-12 01:41
The zone of my ctpu is us-central1-b(region is us-central1).
And I am check the zone of my project(only one project "test")  
$ gcloud compute project-info describe
==========================
commonInstanceMetadata:
  fingerprint: xEyyn4O42FQ=
  items:
  - key: ssh-keys
    value: wxyang1503:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC6P98UKNqzz7dlydF3UBJgPa5+RJAntvAP/1Hi98FAMx5xwL1nMKBnEK92YeYcFHsyIl4fRZc6HcJsrwEwOMwkOEQASmqXV7i+QPqsnOdvhCWpNMxYhs8Np4i4O3M5ehxB6p9o08tNoT6pgH7xeauwGIEgJr4j0jRf85q1f8sS/ZOdDL17ok+EA2dmzeYd/MVrzfUot/XsNfgy5xxAQ0gbePtXbwMGPwj1QP497YTZbZkBMlXTb+eIJNtdfzKuV+iJLxRyWl1P8AzAhUlRKDPqDczD4PqPjtW9eLCZx9TVob1a7zweyey0QCgIySxe3vNMp6iQCDJfvf3zzd7o3ZRT
      wxyang1503@cs-6000-devshell-vm-a5141525-a74e-4a2e-9437-7aa2359aab5e
  kind: compute#metadata
creationTimestamp: '2018-07-07T04:45:18.740-07:00'
defaultServiceAccount: 1094614333223-compute@developer.gserviceaccount.com
id: '5719615354853726497'
kind: compute#project
name: test
==============
I did not see the zone and region infomation？

**Comment by chrislarkin** [comment] 2018-07-12 12:16
Sorry, my last comment was incorrectly worded - I've updated it.

`ctpu cfg` (or `gcloud config list`) will show you the default region/zone that is used in the absence of a `zone` flag. I suspect that there is a mismatch between that value and the zone in which your tpu was created (hence the 403 error). Can you double check your tpu's zone [here](https://console.cloud.google.com/compute/tpus) and confirm that it matches the zone value displayed when running `ctpu cfg`?

If they are mismatched, you can either:

1. Pass the correct zone explicitly, eg `ctpu up --zone=us-central1-b`
2. Update the default zone (linked in my previous reply)

**Comment by yangw502** [comment] 2018-07-13 01:55
I am reset the zone and region, but still hint the 403 error. 
==============
wxyang1503@cloudshell:~ (pospaltest)$ gcloud config set compute/zone us-central1-b
Updated property [compute/zone].
wxyang1503@cloudshell:~ (pospaltest)$ gcloud config set compute/region us-central1
Updated property [compute/region].
wxyang1503@cloudshell:~ (pospaltest)$ ctpu up --zone=us-central1-b
2018/07/13 09:48:38 googleapi: Error 403: Read access to project 'pospaltest' was denied, forbidden
wxyang1503@cloudshell:~ (pospaltest)$ ctpu cfg
ctpu configuration:
        name: wxyang1503
        project: pospaltest
        zone: us-central1-b
If you would like to change the configuration for a single command invocation, please use the command line flags.


By the way, my bill shows an amount of $286.61, can I continue to use tpu ？

**Comment by chrislarkin** [comment] 2018-07-13 13:10
The trace above shows that `gcloud`/`ctpu` are set to us-central1-b, which is a good start.

Please visit the [TPUs section of Cloud Console](https://console.cloud.google.com/compute/tpus). Are there entries in the table? If so, what are their zone values?

Unfortunately I have little insight into billing (aside from my assumption that it is not the cause of this issue); I'd recommend checking out the [Billing Support](https://cloud.google.com/support/billing) page for help there.

**Comment by saeta** [comment] 2018-08-13 23:58
@yangw502 I believe this issue should be fixed in `ctpu` version `1.5`. Please do re-open the issue if you can reproduce the issue!

**Closed by saeta** 2018-08-13 23:58 UTC
