### ISSUE TITLE
"Core halted unexpectedly:" error on a TPUv3-8 when using model parallelism

### ISSUE THREAD

**Issue by shawwn** [tensorflow/tpu#785] opened 2020-06-16 12:41 UTC
Howdy,

Someone on our [ML community discord server](https://github.com/shawwn/tpudiepie#ml-community) reported that their TPUv3-8 was failing with an error. When they posted the logs, the error message was something I've never seen before.

The error was "Core halted unexpectedly:" (The colon isn't a typo; I assume there was more information that was supposed to be present in the error message, but nothing showed up.)

I assume it's because they're using a different TPU version. We mostly use TPU system software 1.15 (and we're reluctantly being forced to upgrade to 1.15.3, though the reasons you want everyone to upgrade are understandable).

I haven't found out which TPU version this user is using. When I do, I'll let you know.

The full log is here: https://gist.github.com/shawwn/8f00d0b7c7e7dd5175f958f26b0138e8

The relevant stack trace:

```
ERROR:tensorflow:Error recorded from training_loop: From /job:worker/replica:0/task:0:
Core halted unexpectedly:
INFO:tensorflow:training_loop marked as finished
WARNING:tensorflow:Reraising captured error
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InternalError: From /job:worker/replica:0/task:0:
Core halted unexpectedly:
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "run_training.py", line 212, in <module>
    main()
  File "run_training.py", line 207, in main
    run(**vars(args))
  File "run_training.py", line 140, in run
    dnnlib.submit_run(**kwargs)
  File "/home/me/stylegan2/dnnlib/submission/submit.py", line 383, in submit_run
    return farm.submit(submit_config, host_run_dir)
  File "/home/me/stylegan2/dnnlib/submission/internal/local.py", line 22, in submit
    return run_wrapper(submit_config)
  File "/home/me/stylegan2/dnnlib/submission/submit.py", line 314, in run_wrapper
    worker(i)
  File "/home/me/stylegan2/dnnlib/submission/submit.py", line 312, in worker
    thunk()
  File "/home/me/stylegan2/dnnlib/submission/submit.py", line 282, in thunk
    run_func_obj(**submit_config.run_func_kwargs)
  File "/home/me/stylegan2/training/training_loop.py", line 676, in training_loop
    estimator.train(input_fn, steps=training_steps)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3035, in train
    rendezvous.raise_errors()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 136, in raise_errors
    six.reraise(typ, value, traceback)
  File "/usr/lib/python3/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3030, in train
    saving_listeners=saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 370, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1161, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1195, in _train_model_default
    saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1494, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/monitored_session.py", line 754, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/monitored_session.py", line 1259, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/monitored_session.py", line 1360, in run
    raise six.reraise(*original_exc_info)
  File "/usr/lib/python3/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/monitored_session.py", line 1345, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/monitored_session.py", line 1418, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/monitored_session.py", line 1176, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: From /job:worker/replica:0/task:0:
Core halted unexpectedly:
```

Note that this is using model parallelism (https://cloud.google.com/tpu/docs/spatial-partitioning) on a TPUv3-8 with the following topology:

```
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:enable_2d_tiling: True
INFO:tensorflow:num_cores_per_replica: 4
INFO:tensorflow:computation_shape: [1, 2, 2]
INFO:tensorflow:num_replicas: 2
INFO:tensorflow:device_assignment.topology.device_coordinates: [[[0 0 0]
  [0 0 1]
  [1 0 0]
  [1 0 1]
  [0 1 0]
  [0 1 1]
  [1 1 0]
  [1 1 1]]]
INFO:tensorflow:device_assignment.core_assignment: [[[0 0 0]
  [0 0 1]
  [0 1 0]
  [0 1 1]]

 [[1 0 0]
  [1 0 1]
  [1 1 0]
  [1 1 1]]]
```

(I wish the logs would print the TPU system software version...)

This codebase runs fine on a TPU pod, so I assume it's barfing when attempting to use a TPUv3-8 because it has relatively few cores in comparison. Also I believe the error is intermittent; they mentioned seeing "about 10 examples per second", so I assume it runs fine sometimes.

Thanks!

*If you found this bug report helpful, please consider [joining my patreon](https://www.shawwn.com/thanks)*

**Comment by xivh** [comment] 2020-06-17 00:15
Downgrading the TPU software from 2.2 to 1.15 fixed the problem.

**Comment by aman2930** [comment] 2020-06-22 21:44
I want to know if the downgraded version which fixed the problem is TF-1.15 or TF-1.15.3?
Also, could you please check the version of the Client VM and TPU is same.

**Comment by xivh** [comment] 2020-06-23 03:20
I downgraded to 1.15 and tensorflow on the VM is also 1.15.

**Comment by aman2930** [comment] 2020-06-26 20:10
Thanks for confirming. It seems that the error is because of different version of TF on Client VM and TPU, which is kind of expected.
TPUs are expected to work with same version of Tensorflow on the Client VM as that of the TPU.

Closing this one for now. Feel free to open it if you see it again.

**Closed by aman2930** 2020-06-26 20:10 UTC
