### ISSUE TITLE
AttributeError: 'module' object has no attribute 'bfloat16_scope'

### ISSUE THREAD

**Issue by czabo** [tensorflow/tpu#194] opened 2018-09-21 11:40 UTC
Got this AttributeError just after running the resnet_main.py. Any idea?
I wrote the command as it is stated in the description.

**Comment by liammdalton** [comment] 2018-09-29 00:07
Hi @czabo!

Which parameters did you run resnet_main.py with? I'd love to try to repro this issue.

**Comment by borosdenes** [comment] 2018-09-29 16:42
Hi @czabo !

I've run into this issue as well and might know a somewhat solution to your question (if the cause is the same, though you could've included your [Traceback](https://en.wikipedia.org/wiki/Stack_trace)). 

I presume the error was thrown at [L300](https://github.com/tensorflow/tpu/blob/master/models/official/resnet/resnet_main.py#L300), which I resolved by directly importing `bfloat16_scope`. First include the following line in your imports.
```
from tensorflow.contrib.tpu.python.tpu.bfloat16 import bfloat16_scope
```
Then change L300 to:
```
    with bfloat16_scope():
```

_Though it's not clear for my why doesn't the initial setup work. I was running the code on GCP on TPU_v2 (tensorflow 1.9)._

**Comment by aman2930** [comment] 2018-10-15 17:48
Hi @czabo !
I hope this issue is fixed. So closing the issue. If you are still getting it, feel free to reopen the issue.

Thanks

**Closed by aman2930** 2018-10-15 17:48 UTC
